# Project: STRcpy
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = 1112.o
LINKOBJ  = 1112.o
LIBS     = -L"F:/Dev-cpp/Dev-Cpp/MinGW64/lib" -L"F:/Dev-cpp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"F:/Dev-cpp/Dev-Cpp/MinGW64/include" -I"F:/Dev-cpp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"F:/Dev-cpp/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"F:/Dev-cpp/Dev-Cpp/MinGW64/include" -I"F:/Dev-cpp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"F:/Dev-cpp/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"F:/Dev-cpp/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = STRcpy.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

1112.o: 1112.c
	$(CC) -c 1112.c -o 1112.o $(CFLAGS)
